name: Deploy to Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: write

jobs:
  build-and-deploy:
    if: >
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Extract changelog for current tag
        id: changelog
        run: |
          TAG=${{steps.get_tag.outputs.tag}}
          echo "TAG is ${TAG}"
          echo "Looking for changelog for tag: $TAG"
          # Cek apakah ada tag selanjutnya
          NEXT_LINE=$(grep -n "## ${TAG}" CHANGELOG.txt | cut -d: -f1)
          if [ -z "$NEXT_LINE" ]; then
          echo "Tag ${TAG} not found in CHANGELOG.txt"
          exit 1
          fi
          # Ambil isi mulai dari tag hingga sebelum tag berikutnya
          CHANGELOG=$(awk -v tag="## ${TAG}" '
          $0 == tag {found=1; next}
          found && /^## / {exit}
          found {print}
          ' CHANGELOG.txt)
          echo "CHANGELOG is ${CHANGELOG}"
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          name: "Release ${{ steps.get_tag.outputs.tag }}"
          body_path: ${{ env.CHANGELOG }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
